Feature/challenge01
k8s-gt/kubernetes-challenges pull request #1
Opened 2023-04-11 01:29 UTC by mvlsqz

2023-04-11 03:00 UTC, jossemarGT requested changes

2023-04-11 03:00 UTC, jossemarGT commented on 01/README.md
> +Una serie de ejercicios para des enpolvar nuestras habilidades
```suggestion
Una serie de ejercicios para desempolvar nuestras habilidades
```

2023-04-11 03:00 UTC, jossemarGT commented on 01/README.md
> +con kubernetes
```suggestion
con Kubernetes
```

2023-04-11 03:00 UTC, jossemarGT commented on 01/README.md
> +Y para los nuevos una demo de como funciona K8s
```suggestion
Y para los nuevos una demo de como funciona Kubernetes
```

2023-04-11 03:00 UTC, jossemarGT commented on 01/README.md
> +## Reto 1 | Descripcion
```suggestion
## Reto 1 - Configurando RBAC y role binding para una aplicación con su usuario
```

2023-04-11 03:00 UTC, jossemarGT commented on 01/README.md
> +Documentacion: **[managing-tls-in-a-cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)**
Me hace pensar que estos pre-requisitos son para ambos escenarios. De ser así considero que debería estar en el README raíz.

2023-04-11 03:00 UTC, jossemarGT commented on 02/README.md
> +## Reto 02 | Descripcion
```suggestion
## Reto 02 - Rescatando el cluster roto
```

2023-04-11 03:00 UTC, jossemarGT commented on README.md
> -# kubernetes-challenges
Hey @mvlsqz me encantan estos retos, podrías por favor mover los pre-requisitos para acá?

2023-04-12 00:57 UTC, mvlsqz commented on 01/README.md
> +Documentacion: **[managing-tls-in-a-cluster](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/)**
que tal @jossemarGT estos pasos aplican unicamente al escenario 1

2023-04-12 00:58 UTC, mvlsqz commented on README.md
> -# kubernetes-challenges
Todos los pre-requisitos estan en el README.md principal ahora, gracias por la sugerencia!

2023-04-12 00:58 UTC, mvlsqz commented on 01/README.md
> +Una serie de ejercicios para des enpolvar nuestras habilidades
Fixed

2023-04-12 00:58 UTC, mvlsqz commented on 01/README.md
> +con kubernetes
Updated

2023-04-12 00:58 UTC, mvlsqz commented on 01/README.md
> +Y para los nuevos una demo de como funciona K8s
Updated

2023-04-12 01:13 UTC, jossemarGT approved these changes

2023-04-12 02:15 UTC, merged